---
- name: Clone prod branch
  ansible.builtin.git:
    repo: "{{ git_web_url | default('git@github.com:HugoKovac/BoilerplateWebServer.git') }}"
    dest: "{{ project_path }}/web_prod"
    accept_hostkey: yes
    single_branch: yes
    version: prod

- name: Clone dev branch
  ansible.builtin.git:
    repo: "{{ git_web_url | default('git@github.com:HugoKovac/BoilerplateWebServer.git') }}"
    dest: "{{ project_path }}/web_dev"
    accept_hostkey: yes
    single_branch: yes
    version: dev

- name: Clone backend
  ansible.builtin.git:
    repo: "{{ git_web_url | default('git@github.com:HugoKovac/BoilerplateBackend.git') }}"
    dest: "{{ project_path }}/backend"
    accept_hostkey: yes
    single_branch: yes
    version: main

- name: Add to safe directory
  shell: |
    git config --global --add safe.directory {{ project_path }}/web_dev
    git config --global --add safe.directory {{ project_path }}/web_prod
    git config --global --add safe.directory {{ project_path }}/backend
    
